name: grype
on:
  workflow_run:
    workflows: [ "sbom" ]
    types: [ "completed" ]
permissions:
  contents: read  
  actions: read
  checks: write
  issues: write
  pull-requests: write
  security-events: write
jobs:
  scan-sbom:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      # SBOM artifact'ını tetikleyen run'dan indir
      - name: Download SBOM artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: sbom.spdx.json
          path: .

      - name: Scan SBOM with Grype
        id: scan
        uses: anchore/scan-action@v5
        with:
          sbom: sbom.spdx.json
          output-format: sarif
          fail-build: false
          severity-cutoff: high

      - name: Save SARIF to file (private repo)
        run: echo "${{ steps.scan.outputs.sarif }}" > grype.sarif

      - name: Upload Grype report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype.sarif
          path: grype.sarif
