name: sbom
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom-cyclonedx.json
          format: cyclonedx-json
